import ReactMarkdown from 'react-markdown';

interface Props {
    intel: string | null;
}

export default function AIIntelPanel({ intel }: Props) {
    if (!intel) {
        return (
            <div className="relative border border-dashed border-white/30 p-10 text-center backdrop-blur-sm">
                <span className="text-4xl block mb-4 opacity-20">✦</span>
                <p className="text-white/70 text-sm tracking-widest uppercase"> Intelligence Pending </p>
                <p className="text-white/40 text-[10px] mt-2 max-w-xs mx-auto">
                    Deep analysis becomes available once you reach the
                    <span className="text-white font-bold ml-1">INTERVIEWING</span> stage.
                </p>
            </div>
        );
    }

    return (
        <div className="relative group">
            {/* Editorial Corner Brackets */}
            <span className="absolute -top-1 -left-1 w-4 h-4 border-t-2 border-l-2 border-white/80" />
            <span className="absolute -bottom-1 -right-1 w-4 h-4 border-b-2 border-r-2 border-white/80" />

            <div className="bg-black/20 border border-white/20 p-8 shadow-2xl backdrop-blur-md">
                <div className="flex items-center justify-between mb-8 border-b border-white/10 pb-4">
                    <div className="flex items-center gap-3">
                        <span className="w-2 h-2 bg-white rounded-full animate-pulse shadow-[0_0_8px_white]" />
                        <h3 className="font-bold text-white text-xs tracking-[0.3em] uppercase">
                            Application Intelligence Report
                        </h3>
                    </div>
                    <span className="text-[10px] text-white/40 tracking-widest uppercase">Classified / Internal</span>
                </div>

                <div className="prose prose-sm prose-invert max-w-none 
          prose-p:text-white/90 prose-p:leading-relaxed prose-p:mb-6
          prose-headings:text-white prose-headings:italic prose-headings:font-black prose-headings:tracking-tight
          prose-h1:text-3xl prose-h1:mb-8 prose-h2:text-xl prose-h2:mb-4 prose-h2:mt-10 prose-h2:border-b prose-h2:border-white/10 prose-h2:pb-2
          prose-strong:text-white prose-strong:font-bold prose-strong:bg-white/10 prose-strong:px-1
          prose-ul:list-none prose-ul:pl-0
          prose-li:relative prose-li:pl-6 prose-li:before:content-['→'] prose-li:before:absolute prose-li:before:left-0 prose-li:before:text-white/40
          prose-blockquote:border-l-4 prose-blockquote:border-white/30 prose-blockquote:bg-white/5 prose-blockquote:py-2 prose-blockquote:px-6 prose-blockquote:italic
        ">
                    <ReactMarkdown>{intel}</ReactMarkdown>
                </div>

                <div className="mt-12 pt-6 border-t border-white/10 flex justify-between items-center text-[9px] tracking-[0.2em] font-medium text-white/40 uppercase">
                    <span>Analysis Generated by {import.meta.env.VITE_LLM_PROVIDER_NAME || 'AI'}</span>
                    <span>End of Report</span>
                </div>
            </div>
        </div>
    );
}
